from typing import Tuple, Any

class VideoCapture:
    def __init__(self, index_or_path: int | str) -> None: ...
    def isOpened(self) -> bool: ...
    def read(self) -> tuple[bool, Any]: ...

def imread(filename: str) -> Any: ...
